## Groups for which motion planning can be performed
groups:
  - right_arm
  - left_arm
  - both_arms
  - upper_body

## Planners associated to each group
right_arm:
  planner_type: JointPlanner
  planner_configs:
    - RRTkConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state

left_arm:
  planner_type: JointPlanner
  planner_configs:
    - RRTkConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state

both_arms:
  planner_type: JointPlanner
  planner_configs:
    - RRTkConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state

upper_body:
  planner_type: JointPlanner
  planner_configs:
    - RRTkConfig1
    - LazyRRTkConfig1
  projection_evaluator: joint_state


## Planner configurations
planner_configs:
  RRTkConfig1:
    type: kinematic::RRT
    range: 0.75

  LazyRRTkConfig1:
    type: kinematic::LazyRRT
    range: 0.75
