## This file should be loaded under <robot description>_collision

default_collision_operations:

  ## Body-arms
  - object1: robot_body
    object2: both_arms
    operation: enable

  - object1: robot_body
    object2: arms_body_no_collision
    operation: disable

  ## Body-hands
  - object1: robot_body
    object2: left_hand
    operation: enable

  - object1: robot_body
    object2: right_hand
    operation: enable

  ## Arm-arm
  - object1: left_arm
    object2: right_arm
    operation: enable

  - object1: arm_arm_l_no_collision
    object2: arm_arm_r_no_collision
    operation: disable

  ## Arm-hand
  - object1: left_hand
    object2: right_arm
    operation: enable

  - object1: left_hand
    object2: upper_left_arm
    operation: enable

  - object1: right_hand
    object2: left_arm
    operation: enable

  - object1: right_hand
    object2: upper_right_arm
    operation: enable

  ## Hand-hand
  - object1: left_hand
    object2: right_hand
    operation: enable
