joint_limits:
  torso_1_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  torso_2_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_1_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_2_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_3_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_4_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_5_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_6_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_left_7_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_1_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_2_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_3_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_4_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_5_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_6_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false
  arm_right_7_joint:
    has_position_limits:     true
    has_velocity_limits:     true
    has_acceleration_limits: true
    max_acceleration:        5.0
    angle_wraparound:        false