## This file should be loaded under <robot description>_planning

groups:

  - name: robot_body
    joints:
      torso_1_joint
      torso_2_joint
    links:
      base_link
      base_cargo_link
      torso_1_link
      torso_2_link
      head_1_link
      head_2_link

  - name: left_arm
    joints:
      arm_left_1_joint
      arm_left_2_joint
      arm_left_3_joint
      arm_left_4_joint
      arm_left_5_joint
      arm_left_6_joint
      arm_left_7_joint
    links:
      arm_left_1_link
      arm_left_2_link
      arm_left_3_link
      arm_left_4_link
      arm_left_5_link
      arm_left_6_link
      arm_left_7_link

  - name: upper_left_arm
    links:
      arm_left_1_link
      arm_left_2_link
      arm_left_3_link
      arm_left_4_link

  - name: right_arm
    joints:
      arm_right_1_joint
      arm_right_2_joint
      arm_right_3_joint
      arm_right_4_joint
      arm_right_5_joint
      arm_right_6_joint
      arm_right_7_joint
    links:
      arm_right_1_link
      arm_right_2_link
      arm_right_3_link
      arm_right_4_link
      arm_right_5_link
      arm_right_6_link
      arm_right_7_link

  - name: upper_right_arm
    links:
      arm_right_1_link
      arm_right_2_link
      arm_right_3_link
      arm_right_4_link

  - name: both_arms
    joints:
      arm_left_1_joint
      arm_left_2_joint
      arm_left_3_joint
      arm_left_4_joint
      arm_left_5_joint
      arm_left_6_joint
      arm_left_7_joint
      arm_right_1_joint
      arm_right_2_joint
      arm_right_3_joint
      arm_right_4_joint
      arm_right_5_joint
      arm_right_6_joint
      arm_right_7_joint
    links:
      arm_left_1_link
      arm_left_2_link
      arm_left_3_link
      arm_left_4_link
      arm_left_5_link
      arm_left_6_link
      arm_left_7_link
      arm_right_1_link
      arm_right_2_link
      arm_right_3_link
      arm_right_4_link
      arm_right_5_link
      arm_right_6_link
      arm_right_7_link

  - name: upper_body
    joints:
      torso_1_joint
      torso_2_joint
      head_1_joint
      head_2_joint
      arm_left_1_joint
      arm_left_2_joint
      arm_left_3_joint
      arm_left_4_joint
      arm_left_5_joint
      arm_left_6_joint
      arm_left_7_joint
      arm_right_1_joint
      arm_right_2_joint
      arm_right_3_joint
      arm_right_4_joint
      arm_right_5_joint
      arm_right_6_joint
      arm_right_7_joint
    links:
      base_link
      torso_1_link
      torso_2_link
      head_1_link
      head_2_link
      arm_left_1_link
      arm_left_2_link
      arm_left_3_link
      arm_left_4_link
      arm_left_5_link
      arm_left_6_link
      arm_left_7_link
      arm_right_1_link
      arm_right_2_link
      arm_right_3_link
      arm_right_4_link
      arm_right_5_link
      arm_right_6_link
      arm_right_7_link

  - name: left_hand
    links:
      hand_left_link # TODO: Update with actual hand model

  - name: right_hand
    links:
      hand_right_link # TODO: Update with actual hand model


  - name: arms_body_no_collision
    links:
      arm_left_1_link
      arm_left_2_link
      arm_right_1_link
      arm_right_2_link

  - name: arm_arm_l_no_collision
    links:
      arm_left_1_link
      arm_left_2_link

  - name: arm_arm_r_no_collision
    links:
      arm_right_1_link
      arm_right_2_link
