# TODO: Compromise: 5mm succeeds often, but is a small margin. 10mm is a good margin, but may require planning retries
# Retries are triggered by the final trajectory check. Maybe we should use a 10mm for planning, and a 5mm padding for checking
default_robot_padding: 0.005
link_padding:
  - link: robot_body
    padding: 0.0
