default_collision_operations:
  - object1: head_mount_xtion_link
    object2: arm_left_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_left_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_left_3_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_left_4_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_left_tool_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_right_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_right_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_right_3_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_right_4_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: arm_right_tool_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_color_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_center_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_footprint_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_laser_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: base_torso_laser_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: caster_left_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: caster_left_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: caster_right_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: caster_right_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: head_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: head_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: stereo_gazebo_l_stereo_camera_frame
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: stereo_gazebo_r_stereo_camera_frame
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: stereo_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: torso_1_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: torso_2_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: wheel_left_link
    operation: disable  # Never in collision
  - object1: head_mount_xtion_link
    object2: wheel_right_link
    operation: disable  # Never in collision