group:             left_arm
kinematics_solver: reem_kinematics_constraint_aware/ReemKinematicsPlugin

left_arm:
  root_name:             torso_2_link
  tip_name:              arm_left_7_link
  max_solver_iterations: 2000
  epsilon:               0.01  # Delta x considered to be near-zero
  max_delta_x:           0.006 # 0.6   m/s x 0.01s
  max_delta_q:           0.03  # 3.0 rad/s x 0.01s
  velik_gain:            1.0

  # Diagonal elements of joint space weight matrix
  joint_weights:
    arm_left_1_joint: 1.0
    arm_left_2_joint: 1.0
    arm_left_3_joint: 1.0
    arm_left_4_joint: 1.0
    arm_left_5_joint: 0.5
    arm_left_6_joint: 1.0
    arm_left_7_joint: 0.5

  # Default posture to use as secondary task
  default_posture:
    arm_left_1_joint:  0.138
    arm_left_2_joint:  0.148
    arm_left_3_joint:  0.342
    arm_left_4_joint:  1.610
    arm_left_5_joint:  1.106
    arm_left_6_joint: -0.108
    arm_left_7_joint: -0.914

