group:             right_arm_torso
kinematics_solver: reem_kinematics_constraint_aware/ReemKinematicsPlugin

right_arm_torso:
  root_name:             base_link
  tip_name:              arm_right_7_link
  max_solver_iterations: 2000
  epsilon:               1e-3 # Delta x considered to be near-zero
  max_delta_x:           6e-3 # 0.6   m/s x 0.01s
  max_delta_q:           3e-2 # 3.0 rad/s x 0.01s
  velik_gain:            1.0

  joint_weights:
    torso_1_joint:     0.25
    torso_2_joint:     0.15
    arm_right_1_joint: 1.0
    arm_right_2_joint: 1.0
    arm_right_3_joint: 1.0
    arm_right_4_joint: 1.0
    arm_right_5_joint: 0.5
    arm_right_6_joint: 1.0
    arm_right_7_joint: 0.5

