default_robot_padding: 0.02
link_padding:
  - link: base_link
    padding: 0.0
  - link: torso_1_link
    padding: 0.0
  - link: torso_2_link
    padding: 0.0
  - link: head_1_link
    padding: 0.0
  - link: head_2_link
    padding: 0.0
